name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        name: Install Python 3.10
        with:
          python-version: '3.10'
      - name: Install tox
        run: python -m pip install tox
      - name: run test
        run: tox -e py310

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        name: Install Python 3.10
        with:
          python-version: '3.8'
      - name: Install pre commit
        run: python -m pip install pre-commit
      - name: run pre-commit
        run: pre-commit run --all --show-diff-on-failure

  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        name: Install Python 3.10
        with:
          python-version: '3.10'
      - name: Install dependecies
        run: python -m pip install build
      - name: create wheel and sdist
        run: python -m build .
      - name: Upload source bundle
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
