default_language_version:
    python: python3.8

repos:
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    - id: black
      pass_filenames: true
-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    - id: flake8
      pass_filenames: true
      # this seems to need to be here in addition to setup.cfg
      exclude: vendored|__init__.py|examples
      additional_dependencies:
      - flake8-tidy-imports
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: check-json
    - id: check-yaml
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: trailing-whitespace
      exclude: .*\.md
    - id: debug-statements
    - id: mixed-line-ending
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.5.0
    hooks:
    - id: setup-cfg-fmt
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
    - id: pyupgrade
      args: ["--py36-plus"]
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: rst-backticks
-   repo: https://github.com/PyCQA/isort
    rev: '5.13.2'  # Use the revision sha / tag you want to point at
    hooks:
    -   id: isort
